apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: productpage-client-mtls
spec:
  host: productpage.apps.bookinfo.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
